plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.5'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.failsafe'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = '17'
}

// Force compiler to run in a separate JVM to avoid JAVA_TOOL_OPTIONS conflicts
tasks.withType(JavaCompile).configureEach {
    options.fork = true
    options.encoding = 'UTF-8'
}

repositories {
    mavenCentral()
}

dependencies {
    // This is the core library for Spring Boot
    implementation 'org.springframework.boot:spring-boot-starter'
    
    // This allows your app to receive REST calls (Web API)
    implementation 'org.springframework.boot:spring-boot-starter-web'
    
    
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

}

tasks.named('test') {
    useJUnitPlatform()
    testLogging {
        showStandardStreams = true
        events "passed", "skipped", "failed"
    }
}