plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.5'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.failsafe'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = '17'
}

repositories {
    mavenCentral()
}

dependencies {
    // This is the core library for Spring Boot
    implementation 'org.springframework.boot:spring-boot-starter'
    
    // This allows your app to receive REST calls (Web API)
    implementation 'org.springframework.boot:spring-boot-starter-web'
    
    // This is the "Fail Safe" messaging library for Kafka
    implementation 'org.springframework.kafka:spring-kafka'
    
    // Lombok makes your Java code cleaner (less boilerplate)
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.kafka:spring-kafka-test'
}

tasks.named('test') {
    useJUnitPlatform()
    testLogging {
        showStandardStreams = true
        events "passed", "skipped", "failed"
    }
}